# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: manipulator
  joint_model_group_pose: zero
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 20
  cycle_time_error_threshold: 0.1
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - motor_b_wheel_joint
    - motor_d_wheel_joint
    - motor_c_wheel_joint
    - motor_a_wheel_joint
  sim_control_mode: 0  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 20
controller_list:
  - name: simple_arm
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - motor_b_wheel_joint
      - motor_d_wheel_joint
      - motor_c_wheel_joint
  - name: gripper
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - motor_a_wheel_joint
