#!/usr/bin/env python3
"""
Starts the serial interface
"""

import argparse
import sys
import rospy
from lego_spike_interface.interfaces import SerialInterface

rospy.init_node('lego_spike_serial_interface')

parser = argparse.ArgumentParser('Serial interface for Lego Mindstorms and Lego Spike Prime hub')
parser.add_argument("-p", "--port", metavar="TTY", type=str, default="/dev/lego", dest='port', help="Serial port to open (default /dev/lego)")
parser.add_argument("-b", "--baud", metavar="INT", type=int, default=115200, dest='baud', help="Serial port to open (default /dev/lego)")
args, unk_args = parser.parse_known_args()

interface = SerialInterface(port=args.port, baud=args.baud)
interface.open()
interface.send_main()
interface.run()
interface.close()
sys.exit(0)
