<?xml version="1.0" ?>
<robot name="lego_arm" xmlns:xacro="http://wiki.ros.org/xacro">
  <xacro:include filename="$(find lego_spike_description)/urdf/lego_materials.urdf.xacro" />
  <xacro:include filename="$(find lego_spike_description)/urdf/lego_hub.urdf.xacro" />
  <xacro:include filename="$(find lego_spike_description)/urdf/lego_base_plate.urdf.xacro" />
  <xacro:include filename="$(find lego_spike_description)/urdf/lego_motor.urdf.xacro" />
  <xacro:include filename="$(find lego_spike_description)/urdf/lego_distance_sensor.urdf.xacro" />
  <xacro:include filename="$(find lego_spike_description)/urdf/lego_color_sensor.urdf.xacro" />

  <link name="base_link" />

  <xacro:lego_base_plate name="base_plate" parent="base_link">
    <origin xyz="0 0 0" rpy="0 0 1.57079" />
  </xacro:lego_base_plate>

  <xacro:lego_hub name="lego_hub" parent="base_plate_top_link">
    <origin xyz="-${lego_stud_spacing * 6} 0 0" rpy="0 0 -${pi/2}" />
  </xacro:lego_hub>
</robot>
