<?xml version="1.0" ?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">
  <xacro:include filename="$(find lego_spike_description)/urdf/lego_dimensions.urdf.xacro" />

  <!--
    Lego Mindstorms 51515 ultrasonic range sensor
    Origin is the center-back, near the cable connection. Emitter & receiver point forward along the X axis.
    Measurements relative to the origin of the model.
  -->
  <xacro:macro name="lego_distance_sensor" params="port parent *origin">
    <link name="distance_${port}_link">
      <visual>
        <geometry>
          <mesh filename="package://lego_spike_description/meshes/SpikePrimeDistanceSensor.stl" scale="0.0004 0.0004 0.0004"/>
        </geometry>
        <material name="lego_white" />
        <origin xyz="${lego_stud_spacing * 1.5} 0 -${lego_stud_spacing * 1.5}" rpy="1.5707963267948966 0 1.5707963267948966" />
      </visual>
      <collision>
        <geometry>
          <box size="${lego_stud_spacing * 4} ${lego_stud_spacing * 7} ${lego_stud_spacing * 3}" />
        </geometry>
        <origin xyz="${lego_stud_spacing * 1.5} 0 0" rpy="0 0 0" />
      </collision>
    </link>
    <joint name="distance_${port}_joint" type="fixed">
      <parent link="${parent}" />
      <child link="distance_${port}_link" />
      <xacro:insert_block name="origin" />
    </joint>
  </xacro:macro>
</robot>
